### ISSUE TITLE
Tutorials link "https://nokogiri.org/tutorials/" is 404

### ISSUE THREAD

**Issue by eastmanjason** [sparklemotion/nokogiri#1870]
![image](https://user-images.githubusercontent.com/43869312/52076979-27aefe00-254d-11e9-9faf-c141895930bd.png)
![image](https://user-images.githubusercontent.com/43869312/52077041-40b7af00-254d-11e9-9996-dd76a772a6bd.png)

**Comment by flavorjones** [comment]
Thanks for reporting this!

:thinking: that's interesting, will look into it.

**Comment by flavorjones** [comment]
It turns out the mkdocs doesn't support linking directly to a nav section; and so I've updated the README and deployed the site.

Thanks again for pointing this out!

**Comment by ConorMcGee** [comment]
This seems to be still broken? Also the 'Tutorials' link on the homepage also seems to be wrong (just links to the homepage).

**Comment by flavorjones** [comment]
What's broken, can you please be more specific on where you were, what you clicked on, and where you went and what you saw?

> It turns out the mkdocs doesn't support linking directly to a nav section; and so I've updated the README and deployed the site.

meaning, I've updated the README to not be a broken link, but still try to indicate that there are tutorials on the site. if there's something that could be made clearer within the constraints of mkdocs, I'm open to it.

**Comment by ConorMcGee** [comment]
Apologies, I thought the original issue was about something slightly different, I think. 

I was talking about the 'Tutorials' link, under 'Links', on the main https://nokogiri.org homepage, which for me appears as:
`<a href="https://nokogiri.org">Tutorials</a>`

Furthermore, when I manually enter the url https://nokogiri.org/tutorials I get a `404`.

I _can_ manually go to https://nokogiri.org/tutorials/parsing_an_html_xml_document.html and that loads fine.

Though, strangely, when I click one of those links on the 404 page, it inserts extra `/tutorials/` into the url every time (recursively, since they all lead to another 404, funnily enough).

Sorry again about being so vague before, and hope this can be of some help. Thanks!
